### ISSUE TITLE
มี List ของ Data News ให้เห็นว่ามีบทความอะไรบ้าง

### ISSUE THREAD

**Issue by zkan** [dataength/daily#11]
อยากเห็น

* หัวข้อ
* คนเขียนบทความ
* ชื่อ source ที่ไปดึงมา
* รูป cover ของบทความ (ถ้ามี)

![Screen Shot 2564-09-10 at 21 16 48](https://user-images.githubusercontent.com/704794/132867789-c49ca1f7-2cad-4ca5-a2a3-0ce41df76a0c.png)

### Tasks

- [ ] แสดง List ของบทความบน iOS
- [ ] Scrape ข่าวมาสัก 1 source => เก็บมาเป็น JSON
- [ ] เอา JSON ใส่ไว้ใน app ตอน build เลย
